# Generated by Django 4.2.4 on 2023-09-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_description_movie_duration_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='end_movie',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_movie',
            field=models.DateField(),
        ),
    ]
